// <auto-generated />
using System;
using CryptoManager.Infrastructure.Persistence.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305101813_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoManager.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("KeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("KeyId");

                    b.Property<int?>("KeyVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Mechanism")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequestId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KeyId");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("CryptoManager.Domain.Entities.Key", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("_allowedMechanismNames")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AllowedMechanisms");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Keys", (string)null);
                });

            modelBuilder.Entity("CryptoManager.Domain.Entities.KeyVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("KeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("KeyId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KeyId", "Version")
                        .IsUnique();

                    b.ToTable("KeyVersions", (string)null);
                });

            modelBuilder.Entity("CryptoManager.Domain.Entities.KeyVersion", b =>
                {
                    b.HasOne("CryptoManager.Domain.Entities.Key", null)
                        .WithMany("Versions")
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CryptoManager.Domain.ValueObjects.ProviderRef", "ProviderRef", b1 =>
                        {
                            b1.Property<Guid>("KeyVersionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ProviderType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("ProviderType");

                            b1.Property<string>("Reference")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("ProviderRef");

                            b1.HasKey("KeyVersionId");

                            b1.ToTable("KeyVersions");

                            b1.WithOwner()
                                .HasForeignKey("KeyVersionId");
                        });

                    b.OwnsOne("CryptoManager.Domain.ValueObjects.PublicKeyMaterial", "PublicKey", b1 =>
                        {
                            b1.Property<Guid>("KeyVersionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Pem")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PublicKeyPem");

                            b1.HasKey("KeyVersionId");

                            b1.ToTable("KeyVersions");

                            b1.WithOwner()
                                .HasForeignKey("KeyVersionId");
                        });

                    b.Navigation("ProviderRef")
                        .IsRequired();

                    b.Navigation("PublicKey")
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoManager.Domain.Entities.Key", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
